-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Erstellungszeit: 09. Aug 2020 um 13:57
-- Server-Version: 10.4.11-MariaDB
-- PHP-Version: 7.2.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

INSERT INTO `recipes` (`id`, `category_id`, `title`, `description`, `instructions`, `servings`, `time`, `rating`, `user_id`, `image`, `created_at`, `updated_at`) VALUES
(1, 4, 'Käsekuchen', 'Der weltbeste Käsekuchen', 'Aus ersten fünf Zutaten einen Knetteig herstellen und diesen gleichmäßig in einer Springform verteilen und bis an den Rand hochziehen. \r\n\r\nDie restlichen Zutaten für die Füllung miteinander mischen und die Quarkmasse in die mit dem Teig ausgekleidete Form füllen. Im vorgeheizten Backofen bei 200 Grad (Umluft 175 Grad) gut eine Stunde backen.\r\n\r\nAchtung: Den Kuchen erst nach dem völligen Erkalten aus der Form nehmen, da unmittelbar nach dem Herausnehmen aus dem Backofen die Konsistenz der Quarkmasse noch zu weich ist.', 12, 30, 5, 1, 'uploads/MM8T94Rdk0gX8wgWH48AQuvPkB1ni57jpLZ8T37E.jpeg', '2020-08-07 20:54:03', '2020-08-07 20:54:03'),
(2, 4, 'Schokomuffins', 'Fluffige Schokomuffins', 'Mehl, Backpulver, Kakao vermengen. Die restlichen Zutaten mit dem Rührgerät schaumig schlagen. Die trockenen Zutaten in hinzufügen und zu einer glatten Masse verrühren. Die Muffins im vorgeheizten Ofen ca. 15 Minuten bei 150° C Umluft backen. Mit einem Zahnstocher testen, ob die Muffins durch sind (Es darf kein Teig mehr daran haften). Die Muffins nach dem Backen sofort aus der Form nehmen und auskühlen lassen.', 12, 30, 5, 1, 'uploads/2MIVzdqBwQgLDaKOuvdchfDKmPRPupco2mBFMxpM.jpeg', '2020-08-07 21:03:36', '2020-08-07 21:03:36'),
(3, 3, 'Spaghetti mit Gemüse', 'Schnelles, leckeres Nudelgericht', 'Spaghetti nach Anleitung kochen. Brokkoli in mundgerechte Röschen zerteilen. Lauch in feine Ringe schneiden. Knoblauch durch die Presse drücken. Das Gemüse mit dem Rosmarin im Olivenöl anbraten, Tomatensauce hinzugeben und mit Salz und Pfeffer abschmecken. Das Gemüse zu den Spaghetti reichen und mit Parmesan bestreuen.', 2, 30, 4, 1, 'uploads/lXk2xkOkJGTmkBYnvBS9rxhOcPd1MqWGTZWwrrYe.jpeg', '2020-08-07 21:13:39', '2020-08-07 21:13:39'),
(4, 1, 'Pizza Funghi', 'Pizza mit frischen Champignons und Basilikum', 'Für den Teig die Hefe in eine Schüssel bröckeln, mit Zucker und ca. 200 ml lauwarmem Wasser glatt rühren. Das Mehl, Olivenöl und 1 TL Salz dazugeben und alles zu einem geschmeidigen Teig verkneten. Zugedeckt an einem warmen Ort ca. 1 Stunde gehen lassen. Den Backofen auf 220°C Ober- und Unterhitze vorheizen.\r\nAus dem Teig 4 Kugeln formen, auf wenig Mehl zu runden Fladen von ca. 24 cm Ø ausrollen, den Rand etwas dicker lassen und auf 4 geölte Pizzableche legen. Mit den Pizzatomaten bestreichen, mit Salz und Pfeffer würzen. Die Champignons putzen und in Scheiben schneiden. Auf den Pizzen verteilen und mit Oregano, Basilikum und dem Käse bestreuen.\r\nIm Backofen ca. 25 Minuten garen, dabei nach der Hälfte der Zeit die Positionen der Bleche im Ofen tauschen.', 2, 120, 4, 1, 'uploads/Md7xt1PdSTX6ZNv3fFoPRJ722Z5rUQr4JqVxxEjW.jpeg', '2020-08-07 21:20:45', '2020-08-07 21:20:45'),
(5, 2, 'Italienischer Salat', 'Leichtes Abendessen oder als Beilage', 'Zuckerschoten in Gemüsebrühe 5 Minuten garen, abschütten und Brühe aufbewahren, Schoten mit kaltem Wasser kurz abspülen. Alle Zutaten in einer Schüssel anrichten, Schafskäse darüberbröseln und geschälte Zwiebel/n in Ringen über den Salat hobeln. Zitronensaft und Paprikapulver mit der Brühe verrühren und über den Salat geben.', 2, 15, 4, 1, 'uploads/SD2TzvNsgPJ8GFxtPGDKB1uwZX9BGBWUOgnPvn6h.jpeg', '2020-08-07 21:28:51', '2020-08-07 21:28:51'),
(6, 4, 'Waffeln', 'Basisrezept für einen Waffelteig', 'Alle Zutaten zu einem zähflüssigen Teig verrühren.', 8, 10, 5, 1, NULL, '2020-08-07 21:38:29', '2020-08-07 21:38:29'),
(7, 4, 'Buttermilk Pancakes', 'Fluffige Pancakes', 'In einer Schüssel Buttermilch und Eier gut verquirlen. \r\n\r\nDie Butter in einem Topf schmelzen, dann beiseitestellen und ein wenig abkühlen lassen. \r\n\r\nIn einer anderen Schüssel Mehl, Salz, Backpulver, Zucker und Vanillezucker mischen. Das Buttermilch-Ei-Gemisch und die zerlassene Butter zu dem Mehlgemisch geben und alles gut verrühren. Den Teig in der Schüssel ruhen lassen, bis die Pfanne heiß ist (ca. 10 Minuten). \r\n\r\nJe Pfannkuchen 1,5 - 2 EL Teig in die mit Fett bestrichene Pfanne geben. Wenn sich an der Oberfläche Bläschen bilden, den Pfannkuchen wenden und auch von der anderen Seite goldbraun backen.', 4, 20, 5, 2, 'uploads/0vd6JeFsxbzk6dIchLmf3YyWSSHXxFypdiAKm6X3.jpeg', '2020-08-07 21:46:38', '2020-08-07 21:46:38'),
(8, 2, 'Joghurt-Salatdressing', 'Zu Blattsalaten oder Gurkensalat', 'Alle Zutaten in einem Shaker gut miteinander vermischen.', 2, 10, 3, 2, NULL, '2020-08-07 21:49:58', '2020-08-07 21:49:58');

